import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  //   const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);


  return (
    <>
      <Head>
        <title>P3 | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:grid md:grid-cols-2">
        <section className="md:p-2 text-center h-screen flex flex-col justify-center align-center">
          <div>
            <h1 className="transition text-2xl md:text-3xl text-gray-700">Ping Pong Leaderboard</h1>
            <p>Yep, it's finally done!</p>
            <div className="mt-8">
              <Link href="/register">
                <button className="font-medium w-32 border-2 border-blue-500 m-2 p-2 rounded text-blue-500">
                  Register
                </button>
              </Link>

              <Link href="/login">
                <button className="font-medium w-32 border-2 border-blue-500 m-2 p-2 rounded bg-blue-500 text-white hover:bg-blue-600">
                  Login
                </button>
              </Link>
            </div>
          </div>
        </section>
        <section className="hidden md:block">
          <div className="relative h-screen">
            <Image src="/images/pingpong.jpg" layout="fill" objectFit="cover" />
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
